// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-V56hCLW0dU50m1yIzf6q1cC6uIJ2th0',
    appId: '1:398774255712:web:afc114cce2e9270f2cc305',
    messagingSenderId: '398774255712',
    projectId: 'soloforte-106c8',
    authDomain: 'soloforte-106c8.firebaseapp.com',
    storageBucket: 'soloforte-106c8.firebasestorage.app',
    measurementId: 'G-GXFT7PGTNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd3Xmr1w0FU4mcgHXH2KEaOFixg7ngvn0',
    appId: '1:540665358389:android:3171e5b6e7aeef63e9a97c',
    messagingSenderId: '540665358389',
    projectId: 'flowagro-8c3bc',
    storageBucket: 'flowagro-8c3bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd3Xmr1w0FU50m1yIzf6q1cC6uIJ2th0',
    appId: '1:540665358389:ios:3171e5b6e7aeef63e9a97c',
    messagingSenderId: '540665358389',
    projectId: 'flowagro-8c3bc',
    storageBucket: 'flowagro-8c3bc.firebasestorage.app',
    iosBundleId: 'com.example.soloforteApp',
  );
}
